# Generated by Django 2.0.13 on 2020-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
